#!/bin/bash
# https://github.com/PiDroid-B/docker-compose-recursive
# MIT ©2022 PiDroid-B 

_get_##MYAPP##()
{
  local current=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=()

  # $1 is the name of the command 
  # $2 is the word being completed
  # $3 is the word preceding the word being completed

  commands="-h -u -d -r -p -i -f -c -v"
  folders="$(##MYAPP## -c)"

  if [[ "$1" == "$3" ]]; then
      COMPREPLY=( $( compgen -o nosort -W "$commands $folders" -- $2 ) )
  else
      COMPREPLY=( $( compgen -o nosort -W "$commands" -- $2 ) )
  fi
}

complete -F _get_##MYAPP## ##MYAPP##