#!/bin/bash
# https://github.com/PiDroid-B/docker-compose-recursive
# MIT ©2022 PiDroid-B

_get_@@MYAPP@@()
{
  local current=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=()

  # list of options
  local cmd="hudrpifcv"

  # $1 is the name of the command
  # $2 is the word being completed
  # $3 is the word preceding the word being completed

  local result_cmd=""
  for (( i=0; i<${#cmd}; i++ )); do
    result_cmd+="-${cmd:$i:1} "
  done

  if [[ "$1" == "$3" ]]; then
      folders="$(@@MYAPP@@ -c)"
      COMPREPLY=( $( compgen -o nosort -W "$result_cmd $folders" -- $2 ) )
  else
      COMPREPLY=( $( compgen -o nosort -W "$result_cmd" -- $2 ) )
  fi
}

complete -F _get_@@MYAPP@@ @@MYAPP@@
